const ROUTES = {
  'br': {
    HOME: '/',
    FORGOT_PASSWORD: "/esqueceu-senha",
    REDIFINE_PASSWORD: "/redefinir-senha",
    REGISTER: "/novo-cadastro",
    CONFIRM_REGISTRATION: "/confirmar-cadastro",
    DASHBOARD: "/painel-de-controle",
    PROFILE: "/perfil",
    PAYMENTS: "/pagamentos",
    NEW: "/cadastrar",
    EVENTS: "/eventos",
  },
  'en': {
    HOME: '/',
    FORGOT_PASSWORD: "/forgot-password",
    REDIFINE_PASSWORD: "/reset-password",
    REGISTER: "/registration",
    CONFIRM_REGISTRATION: "/confirm-registration",
    DASHBOARD: "/dashboard",
    PROFILE: "/profile",
    PAYMENTS: "/payments",
    NEW: "/new",
    EVENTS: "/events",
  },
  'es': {
    HOME: '/',
    FORGOT_PASSWORD: "/olvide-contrasena",
    REDIFINE_PASSWORD: "/redefinir-contrasena",
    REGISTER: "/registro",
    CONFIRM_REGISTRATION: "/confirmar-registro",
    DASHBOARD: "/panel-de-control",
    PROFILE: "/perfil",
    PAYMENTS: "/pagos",
    NEW: "/nuevo",
    EVENTS: "/eventos",
  },
}

export default ROUTES;
