export default {
	HOME: '/',
	FORGOT_PASSWORD: '/forgot-password',
	REDIFINE_PASSWORD: '/reset-password',
	REGISTER: '/registration',
	CONFIRM_REGISTRATION: '/confirm-registration',
	DASHBOARD: '/dashboard',
	ALERTS: '/alerts',
	PROFILE: '/profile',
	PAYMENTS: '/payments',
	NEW: '/new',
	EDIT: '/edit',
	SUBSCRIPTIONS: '/subscriptions',
	EVENTS: '/events',
	SURVEYS: '/surveys',
};
