export default {
	HOME: '/',
	FORGOT_PASSWORD: '/olvide-contrasena',
	REDIFINE_PASSWORD: '/redefinir-contrasena',
	REGISTER: '/registro',
	CONFIRM_REGISTRATION: '/confirmar-registro',
	DASHBOARD: '/panel-de-control',
	ALERTS: '/alertas',
	PROFILE: '/perfil',
	PAYMENTS: '/pagos',
	NEW: '/nuevo',
	EDIT: '/editar',
	SUBSCRIPTIONS: '/suscripciones',
	EVENTS: '/eventos',
	SURVEYS: '/encuestas',
};
